### ISSUE TITLE
ImportError: cannot import name 'SimpleQueue'

### ISSUE THREAD

**Issue by ayoubu** [davidcaron/pclpy#104]
```
import pclpy
from pclpy import pcl

point_cloud = pclpy.read("street.las", "PointXYZRGBA")
mls = pcl.surface.MovingLeastSquaresOMP.PointXYZRGBA_PointNormal()
tree = pcl.search.KdTree.PointXYZRGBA()
mls.setSearchRadius(0.05)
mls.setPolynomialFit(False)
mls.setNumberOfThreads(12)
mls.setInputCloud(point_cloud)
mls.setSearchMethod(tree)
mls.setComputeNormals(True)
output = pcl.PointCloud.PointNormal()
mls.process(output)
```

When I run the above code, I get this error:

Traceback (most recent call last):
  File ".../test_pclpy/test_pcl01.py", line 1, in <module>
    import pclpy
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/pclpy/__init__.py", line 5, in <module>
    from pclpy.io.functions import read
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/pclpy/io/__init__.py", line 3, in <module>
    from .functions import read
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/pclpy/io/functions.py", line 3, in <module>
    from . import las
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/pclpy/io/las.py", line 2, in <module>
    import laspy
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/laspy/__init__.py", line 6, in <module>
    from .copc import CopcReader, Bounds
  File ".../miniconda3/envs/pcl_view_1/lib/python3.6/site-packages/laspy/copc.py", line 8, in <module>
    from queue import Queue, SimpleQueue
ImportError: cannot import name 'SimpleQueue'

**Comment by HalvesChen** [comment]
Hi! I have the same problem, how do you solve it?

**Comment by nulltofull** [comment]
Follow your error path to find the copc.py。 
from queue import Queue, SimpleQueue。 
Modified as: from queue import Queue; from multiprocessing import SimpleQueue
