### ISSUE TITLE
pip install pypi

### ISSUE THREAD

**Issue by WillingDil** [davidcaron/pclpy#48]
安装成功之后   import pclpy 提示下面的错误

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python36\lib\site-packages\pclpy\__init__.py", line 3, in <module>
    import pclpy.pcl as pcl
ImportError: DLL load failed: 找不到指定的模块。

**Comment by niranjanreddy891** [comment]
Install OpenNI2, it will solve the issue. Make sure you copy C:\Program Files\OpenNI2\Samples\Bin\OpenNI2.dll.Copy OpenNI2.dll to Lib\site-packages\python_pcl-0.3-py3.6-win-amd64.egg\pcl

**Comment by lfhgljj** [comment]
I also have the same problem.but there is no "python_pcl-0.3-py3.6-win-amd64.egg" in “site-packages”.The same situation occurred when I used “pip” to install it.
I installed it directly using pycharm. Pycharm uses the local environment. The computer has installed pcl(1.8.1，2015). By the way , I used python3.6.
How can I fix it?

**Comment by lfhgljj** [comment]
After a day of hard work, I have I finally solved the problem。After trying various methods, I used a relatively silly method. I deleted the ".PyCharm2019.2" folder and reimported the local interpreter.
Although the problem was solved, the reason was still unclear. If anyone knows the reason, please help me explain the reason when you are free. Grateful!

**Comment by danielemarchisio** [comment]
I had the same problem, but after some time, I decided to copy all .dll files from pclpy_dependencies to pclpy folder and this worked for me! Don't know why

**Comment by bernland** [comment]
I experienced the exact same problem and solved it by recovering the file "C:\WINDOWS\System32\msvcr100.dll" from another system.

I hope this helps!

**Comment by CRIGIM** [comment]
I have the same issue. None of the proposed solution is working for me

**Comment by ankus-wu** [comment]
you may need to install c++ tools in Visual Studio Installer

**Comment by xyuhuang** [comment]
> I had the same problem, but after some time, I decided to copy all .dll files from pclpy_dependencies to pclpy folder and this worked for me! Don't know why

I did this and  it works for pclpy. BUT then it went wrong with import pcl. Is there a conflict between them? They don't seem to work at the same time.
